export const heroes = [
  {
    id: 1,
    name: "Power to the Apes",
    description:
      "Use the Power to the Apes deck and destroy your opponents using bleed damage",
    starterdeck: [
      "Defend",
      "Defend",
      "Defend",
      "Defend",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Bash",
    ],
    deckname: "defaultDeck",
    type: "Normal",
    image: "PTTA.gif",
    background: "p2a.png",
  },
  {
    id: 2,
    name: "Specter",
    description:
      "Specter uses evasive manouvres and poisonous skills to win his battles.",
    starterdeck: [
      "Defend",
      "Defend",
      "Defend",
      "Defend",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Bash",
    ],
    deckname: "defaultDeck",
    type: "Poison",
    image: "hero1.gif",
    background: "specter.jpeg",
  },
  {
    id: 3,
    name: "Ice Cream",
    description:
      "General Ice Cream will obliterate enemies using his ice abilities!",
    starterdeck: [
      "Defend",
      "Defend",
      "Defend",
      "Defend",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Bash",
    ],
    deckname: "defaultDeck",
    type: "Ice",
    image: "ice_v1.gif",
    background: "ice.jpeg",
  },
  {
    id: 4,
    name: "Sakura",
    description: "Coming soon",
    starterdeck: [
      "Defend",
      "Defend",
      "Defend",
      "Defend",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Bash",
    ],
    deckname: "defaultDeck",
    type: "Wind",
    image: "hero1.gif",
    background: "sakura.jpeg",
  },
];
