export const heroes = [
  {
    id: 1,
    name: "Power to the Apes",
    description:
      "Use the Power to the Apes deck and destroy your opponents using bleed damage",
    starterdeck: [
      "Defend",
      "Defend",
      "Defend",
      "Defend",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Bash",
    ],
    deckname: "defaultDeck",
    type: "Normal",
    image: "PTTA.gif",
    background: "p2a.png",
    thumbnail: "p2a.png",
  },
  {
    id: 2,
    name: "Specter",
    description:
      "Specter uses evasive manouvres and poisonous skills to win his battles.",
    starterdeck: [
      "Poison dart",
      "Poison dart",
      "Poison dart",
      "Poison mist",
      "Poison mist",
      "Poison mist",
      "Defend",
      "Defend",
      "Defend",
      "Defend",
    ],
    deckname: "poison",
    type: "Poison",
    image: "hero1.gif",
    background: "specter.jpeg",
    thumbnail: "specter.png",
  },
  {
    id: 3,
    name: "Ice Cream",
    description:
      "General Ice Cream will obliterate enemies using his ice abilities!",
    starterdeck: [
      "Electric shock",
      "Electric shock",
      "Electric shock",
      "Electric shock",
      "Battery Pills",
      "Battery Pills",
      "Battery Pills",
      "Black Lightning",
      "Thunder storm",
      "Thunder storm",
    ],
    deckname: "electric",
    type: "Ice",
    image: "ice_v1.gif",
    background: "ice.jpeg",
    thumbnail: "ice.png",
  },
  {
    id: 4,
    name: "Sakura",
    description: "Coming soon",
    starterdeck: [
      "Defend",
      "Defend",
      "Defend",
      "Defend",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Strike",
      "Bash",
    ],
    deckname: "defaultDeck",
    type: "Wind",
    image: "hero1.gif",
    background: "sakura.jpeg",
    thumbnail: "sakura.png",
  },
];
